Create CONTRIBUTING.md
thisHermit/fantastic-broccoli pull request #2
Opened 2019-12-31 10:12 UTC by thisHermit

2020-01-01 04:49 UTC, amjaps commented on CONTRIBUTING.md
> +  * [Specs Styleguide](#specs-styleguide)
Shouldn't we use Dart Styleguide?

2020-01-01 04:50 UTC, amjaps requested changes
Everything is fine. There are some lines mentioning about javascript, CoffeeScript, and Python files

2020-01-01 05:03 UTC, thisHermit commented on CONTRIBUTING.md
> +  * [Specs Styleguide](#specs-styleguide)
Sure, will fix that.

2020-01-01 05:06 UTC, thisHermit reviewed
Sure will do that

2020-01-02 17:53 UTC, amjaps approved these changes

2020-01-02 18:13 UTC, merged